---
title: "UGR Muestreo Tema 4"
author: "franmarq@gmail.com"
date: '2022-11-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r data}
data<-read.table("granjas.txt", header = TRUE)
head(data)
attach(data)
y<-data$y
x<-data$x
```



```{r calculos}
library(sampling)
# tama~no de la muestra 
n=27 
N=120
media=31.2

# vector de probabilidades de inclusi´on para un m.a.s 
pik=rep(n/N,n) 

# matriz de probabilidades de inclusi´on para un m.a.s 
pikl=matrix(n*(n-1)/(N*(N-1)),n,n) 

# c´alculo del estimador de Horvitz-Thompson para el total poblacional 
t_ypi=HTestimator(y,pik)

```



```{r modelo}
# definici´on del modelo de superpoblación y = beta*xi + v(xi)uii 
v=x**0.5
modelo=y~x+v
modelo
```


```{r estreg}
tx=sum(x)
tv=sum(v)
total=c(tx,tv)
total

#totales=c(tx1,tx2) 

# c´alculo del estimador de regresi´on 0 
r=regest(formula=modelo, weights= 1/pik, Tx=total, pikl, n) 

# estimador de regresi´on 
t_ygreg=r$regest 
med_ygreg=t_ygreg/N
med_ygreg

# coeficientes 
coef=r$coefficients 
coef
```

```{r plotsampling}
rx<-data.frame(r$x,r$y)
rx
plot(rx$x,rx$y)

data$estim<-r$y

plot(data$x,data$estim)
```

```{r plot2}
rx2<-data(r$x,r$y)
rx
plot(rx$x,rx$y)

```



```{r estimacion}
yestim<- 160286.099+7862.303*31.2-(65839.265/31.2)
yestim


```
